Refactor/reportEntity : 신고 Entity 수정
sixes-sense/back-end pull request #89
Opened 2023-09-13 00:39 UTC by kny3037

## ✨(#72 신고 Entity 수정 ) 

## ✏️내용
- 관리자 숨김 상태 추가
- Boolean 변수 is 추가
- LocalDate -> LocalDateTime

## 📸스크린샷

## 🎁참고사항

2023-09-14 00:02 UTC, bbbbooo approved these changes
확인했습니다. 코멘트 확인 부탁드려요~

2023-09-14 00:02 UTC, bbbbooo commented on src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
> +    private LocalDateTime reportDate;
현재 클래스의 reportDate 자료형과 CreateReportResponse 클래스 내 reportDate 자료형이 일치하지 않아서 오류가 나는거 같습니다.

2023-09-14 00:11 UTC, bbbbooo commented on src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
> +    private LocalDateTime reportDate;
```java
// CreateReportResponse.java
public class CreateReportResponse {

   ....

    private LocalDate reportDate;

   ....

    public static CreateReportResponse fromReport(Report report) {
        ReportType reportType = report.getReportType();

        return CreateReportResponse.builder()
                .reportNo(report.getReportNo())
                .reportTypeLabel(reportType.getKoreanLabel()) // 한국어 레이블 사용
                .reportContent(report.getReportContent())
                .reportDate(report.getReportDate())
                .reviewNo(report.getReviewInfoVO().getReviewNo())
                .build();
    }
}


---------------------------------------------------------------

// Report.java
public class Report {

   ...
  
    @Column(name = "report_date")
    private LocalDateTime reportDate;

```

CreateReportResponse 클래스의 필드값인 reportDate는 LocalDate로 지정되어있으나 Report 엔티티의 필드값인 reportDate는 LocalDateTime으로 지정되어있습니다.

2023-09-14 06:59 UTC, kny3037 commented on src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
> +    private LocalDateTime reportDate;
코멘트 확인했습니다!! 감사합니다! 수정하겠습니다 :)

2023-10-06 01:06 UTC, myrhymetree commented on src/main/java/com/sixesSense/recorder/report/command/domain/aggregate/entity/Report.java
> +    private LocalDateTime reportDate;
> 코멘트 확인했습니다!! 감사합니다! 수정하겠습니다 :)

수정된건가요?

2023-10-06 01:10 UTC, myrhymetree requested changes
테스트쪽 수정되면 알려주세요

2023-10-06 01:50 UTC, myrhymetree approved these changes

2023-10-06 01:50 UTC, merged